# Generated by Django 2.2.3 on 2019-07-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='file_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
