# Generated by Django 2.2.3 on 2019-08-05 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_auto_20190731_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='pub_date',
        ),
    ]
