# Generated by Django 2.2.3 on 2019-08-06 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_remove_blog_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='pubdate',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='file_name',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
